# Site settings
title: Johnry Mangonon
email: johnrymangonon@outlook.com
description: Johnry's Website
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://johnry.com" # the base hostname & protocol for your site
twitter_username: hi_johnry
github_username:  JohnryM
footer_heading: Info

# Top navigation list
page_list:
    About: '/about'

# Footer stuff
reserve_note: © 2021. All rights reserved


# Build settings
markdown: kramdown
highlighter: pygments
timezone: Europe/London
encoding: utf-8
