# Site settings
title: Johnry Mangonon
email: johnrymangonon@outlook.com
description: Johnry's Website of awesomeness
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: hi_johnry
github_username:  Skeenoes
footer_heading: Details

# Top navigation list
page_list:
    About: '/about'
    Cake:  '/cake'
    Feed:  '/feed.xml'

# Footer stuff
reserve_note: © 2015. All rights reserved


# Build settings
markdown: kramdown
highlighter: rouge
timezone: Europe/London
encoding: utf-8
